# -*- coding: utf-8 -*-
"""Solemne 3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jQSgPBp_6ua9_Gu2bie0DwZTLfilKo3U
"""

import streamlit as st
import pandas as pd
import requests

#titulo de la app
st.title("Pokedex Stats")

def obtener_datos_pokemon(nombre):
    #convertimos el nombre a minusculas porque la API lo exige así
    nombre = nombre.lower()
    url = f"https://pokeapi.co/api/v2/pokemon/{nombre}"
    try:
        response = requests.get(url)
        response.raise_for_status() # lanza un error para codigos de estado HTTP incorrectos
        datos_pokemon = response.json()
        return datos_pokemon
    except requests.exceptions.HTTPError as http_err: # toda esta seccion es para evitar errores
        st.error(f"error HTTP al obtener datos de {nombre}: {http_err}")
        return None
    except requests.exceptions.ConnectionError as conn_err:
        st.error(f"error de conexión al obtener datos de {nombre}: {conn_err}")
        return None
    except requests.exceptions.Timeout as timeout_err:
        st.error(f"tiempo de espera agotado al obtener datos de {nombre}: {timeout_err}")
        return None
    except requests.exceptions.RequestException as req_err:
        st.error(f"error inesperado al obtener datos de {nombre}: {req_err}")
        return None



"""# Task
Add the Pokemon's type(s) to the Streamlit app by extracting the type names from the `pokemon_data` and displaying them using a DataFrame. This will be added to the existing display elements in the `640d9ed5` cell.

## Mostrar tipo(s) del Pokémon

### Subtask:
Extraer y mostrar el/los tipo(s) del Pokémon en la interfaz de usuario. Esto implica acceder a la sección 'types' de los datos de la API y presentarlo de forma clara, quizás como una lista o etiquetas.

**Reasoning**:
The subtask requires extracting and displaying the Pokémon's types. I will add a subheader for types, extract the type names using a list comprehension from the 'types' section of the pokemon_data, create a Pandas DataFrame from these types, and then display this DataFrame in the Streamlit app without showing the index.
"""

pokemon_name = st.text_input("ingresa el nombre del pokemon:", "pikachu")
if pokemon_name:
    pokemon_data = obtener_datos_pokemon(pokemon_name)
    if pokemon_data:
        st.subheader(f"datos de {pokemon_data['name'].capitalize()}:")

        col1, col2 = st.columns(2)
        with col1:
            st.metric(label="ID", value=pokemon_data['id'])
        with col2:
            st.metric(label="altura (m)", value=pokemon_data['height'])

        st.metric(label="peso (kg)", value=pokemon_data['weight'])

        st.write("### habilidades:") # titulos
        abilities_list = [ability['ability']['name'] for ability in pokemon_data['abilities']]
        abilities_df = pd.DataFrame(abilities_list, columns=['habilidad'])
        st.dataframe(abilities_df, hide_index=True)

        st.write("### Tipos:")
        types_list = [type_entry['type']['name'] for type_entry in pokemon_data['types']]
        types_df = pd.DataFrame(types_list, columns=['tipo'])
        st.dataframe(types_df, hide_index=True)

        st.write("### estadísticas Base:")
        stats_data = []
        for stat_entry in pokemon_data['stats']:
            stat_name = stat_entry['stat']['name'].replace('-', ' ').title()
            base_stat = stat_entry['base_stat']
            stats_data.append({'estadistica': stat_name, 'valor base': base_stat})

        stats_df = pd.DataFrame(stats_data)
        stats_df = stats_df.set_index('estadistica')
        st.bar_chart(stats_df)

    else:
        st.write("no se pudieron obtener los datos del Pokemon.")